language: cpp

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      before_install:
        - pip install conan
      script:
        - cd toric_landscape && ls && ./build.sh
      env:
        GENERATOR="Unix Makefile"

    - os: windows
      compiler: msvc19
      before_install:
        - choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional"
        - choco install visualstudio2019-workload-vctools
        - choco install conan
      script:
        - cd toric_landscape && dir && build.bat
      env:
        GENERATOR="Visual Studio 16 2019"
