language: cpp


env:
  - project_dir=toric_landscape
  - project_dir=cubemap
  - project_dir=fractal
  - project_dir=metaballs

os: linux
dist: bionic
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-10
before_install:
  - echo Module $project_dir
  - export CXX=g++-10
  - pip install conan
  - export GENERATOR="Unix Makefile"

  
script:
  - cd $project_dir && ls && ./build.sh

# - os: windows                           ## Tinyobjloader hash mismatch
#   before_install:
#     - echo Module $project_dir
#     - choco install conan
#     - export PATH="/c/Program Files/Conan/conan:$PATH"
#     - conan -v
#     - choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional"
#     - choco install visualstudio2019-workload-vctools
#     - set GENERATOR="Visual Studio 16 2019"
#   script:
#     - cd $project_dir && dir
#     - MKDIR build
#     - cd build
#     - conan install ..
#     - cmake .. -G "Visual Studio 16 2019"
#     - cmake --build . --config Release
      
